-- DATA QUALITY ASSESSMENT & BUSINESS RULES
-- =========================================
-- Flight Data Quality Issues Analysis and Resolution
-- Based on sample data analysis from flights_data_exploration_001.csv

USE DATABASE RECRUITMENT_DB;
USE SCHEMA CANDIDATE_00395;

-- ====================
-- 1. DATA QUALITY ISSUES IDENTIFICATION
-- ====================

-- Issue 1: Inconsistent Boolean Values
-- Problem: CANCELLED and DIVERTED fields contain mixed formats
-- Sample values found: 'True', 'False', '1', '0', 'Y', 'N', 'F', 'T'
SELECT 
    'Boolean Inconsistencies' AS "ISSUE_TYPE",
    COUNT(*) AS "TOTAL_RECORDS",
    COUNT(DISTINCT "CANCELLED") AS "CANCELLED_VARIATIONS",
    COUNT(DISTINCT "DIVERTED") AS "DIVERTED_VARIATIONS"
FROM "STAGING_FLIGHTS_RAW";

-- Show actual boolean variations
SELECT 
    "CANCELLED",
    "DIVERTED", 
    COUNT(*) AS "RECORD_COUNT"
FROM "STAGING_FLIGHTS_RAW"
GROUP BY "CANCELLED", "DIVERTED"
ORDER BY "RECORD_COUNT" DESC;

-- Issue 2: Contaminated Text Fields
-- Problem: Airline and airport names contain concatenated codes/descriptions
-- Examples: "DL: Delta Air Lines Inc.", "CharlestonSC: Charleston AFB/International"
SELECT 
    'Text Field Contamination' AS "ISSUE_TYPE",
    COUNT(CASE WHEN "AIRLINENAME" LIKE '%:%' THEN 1 END) AS "CONTAMINATED_AIRLINES",
    COUNT(CASE WHEN "ORIGAIRPORTNAME" LIKE '%:%' THEN 1 END) AS "CONTAMINATED_ORIGIN_AIRPORTS",
    COUNT(CASE WHEN "DESTAIRPORTNAME" LIKE '%:%' THEN 1 END) AS "CONTAMINATED_DEST_AIRPORTS",
    COUNT(*) AS "TOTAL_RECORDS"
FROM "STAGING_FLIGHTS_RAW";

-- Issue 3: Time Format Complexity & Invalid Values
-- AVIATION TIME DEFINITIONS:
-- DEPTIME/ARRTIME: Actual departure/arrival times (HHMM format)
-- CRSDEPTIME/CRSARRTIME: Scheduled departure/arrival times (HHMM format)  
-- WHEELSOFF: Time when aircraft wheels leave the ground (takeoff)
-- WHEELSON: Time when aircraft wheels touch the ground (landing)
-- TAXIOUT/TAXIIN: Taxi time in minutes (duration, not time)
-- DEPDELAY/ARRDELAY: Delay in minutes (positive=late, negative=early)
-- CRSELAPSEDTIME/ACTUALELAPSEDTIME: Flight duration in minutes (not HHMM time format)

SELECT 
    'Time Format Issues' AS "ISSUE_TYPE",
    COUNT(CASE WHEN LENGTH("DEPTIME") BETWEEN 3 AND 4 AND "DEPTIME" NOT LIKE '%:%' THEN 1 END) AS "INTEGER_FORMAT_TIMES",
    COUNT(CASE WHEN "DEPTIME" IS NULL AND "CANCELLED" != '1' AND "CANCELLED" != 'True' THEN 1 END) AS "MISSING_TIMES_NON_CANCELLED",
    
    -- CRITICAL: Invalid time values (2400+ should be 0000-2359) for TIME fields
    COUNT(CASE WHEN TRY_CAST("DEPTIME" AS INTEGER) >= 2400 THEN 1 END) AS "INVALID_DEPTIME_2400_PLUS",
    COUNT(CASE WHEN TRY_CAST("ARRTIME" AS INTEGER) >= 2400 THEN 1 END) AS "INVALID_ARRTIME_2400_PLUS", 
    COUNT(CASE WHEN TRY_CAST("CRSDEPTIME" AS INTEGER) >= 2400 THEN 1 END) AS "INVALID_CRSDEPTIME_2400_PLUS",
    COUNT(CASE WHEN TRY_CAST("CRSARRTIME" AS INTEGER) >= 2400 THEN 1 END) AS "INVALID_CRSARRTIME_2400_PLUS",
    COUNT(CASE WHEN TRY_CAST("WHEELSOFF" AS INTEGER) >= 2400 THEN 1 END) AS "INVALID_WHEELSOFF_2400_PLUS",
    COUNT(CASE WHEN TRY_CAST("WHEELSON" AS INTEGER) >= 2400 THEN 1 END) AS "INVALID_WHEELSON_2400_PLUS",
    
    -- Invalid minute values (should be 00-59) for TIME fields
    COUNT(CASE WHEN MOD(TRY_CAST("DEPTIME" AS INTEGER), 100) >= 60 THEN 1 END) AS "INVALID_DEPTIME_MINUTES",
    COUNT(CASE WHEN MOD(TRY_CAST("ARRTIME" AS INTEGER), 100) >= 60 THEN 1 END) AS "INVALID_ARRTIME_MINUTES",
    COUNT(CASE WHEN MOD(TRY_CAST("CRSDEPTIME" AS INTEGER), 100) >= 60 THEN 1 END) AS "INVALID_CRSDEPTIME_MINUTES",
    COUNT(CASE WHEN MOD(TRY_CAST("CRSARRTIME" AS INTEGER), 100) >= 60 THEN 1 END) AS "INVALID_CRSARRTIME_MINUTES",
    COUNT(CASE WHEN MOD(TRY_CAST("WHEELSOFF" AS INTEGER), 100) >= 60 THEN 1 END) AS "INVALID_WHEELSOFF_MINUTES",
    COUNT(CASE WHEN MOD(TRY_CAST("WHEELSON" AS INTEGER), 100) >= 60 THEN 1 END) AS "INVALID_WHEELSON_MINUTES",
    
    -- DURATION field validation (these are minutes, not HHMM time format)
    COUNT(CASE WHEN TRY_CAST("CRSELAPSEDTIME" AS INTEGER) < 0 THEN 1 END) AS "NEGATIVE_SCHEDULED_DURATION",
    COUNT(CASE WHEN TRY_CAST("ACTUALELAPSEDTIME" AS INTEGER) < 0 THEN 1 END) AS "NEGATIVE_ACTUAL_DURATION",
    COUNT(CASE WHEN TRY_CAST("CRSELAPSEDTIME" AS INTEGER) > 1440 THEN 1 END) AS "EXCESSIVE_SCHEDULED_DURATION",  -- >24 hours
    COUNT(CASE WHEN TRY_CAST("ACTUALELAPSEDTIME" AS INTEGER) > 1440 THEN 1 END) AS "EXCESSIVE_ACTUAL_DURATION",  -- >24 hours
    
    -- DELAY field validation (minutes: positive=late, negative=early)
    COUNT(CASE WHEN TRY_CAST("DEPDELAY" AS INTEGER) < -180 THEN 1 END) AS "EXTREMELY_EARLY_DEPARTURE",  -- >3 hours early
    COUNT(CASE WHEN TRY_CAST("ARRDELAY" AS INTEGER) < -180 THEN 1 END) AS "EXTREMELY_EARLY_ARRIVAL",    -- >3 hours early
    COUNT(CASE WHEN TRY_CAST("DEPDELAY" AS INTEGER) > 600 THEN 1 END) AS "EXTREMELY_LATE_DEPARTURE",    -- >10 hours late
    COUNT(CASE WHEN TRY_CAST("ARRDELAY" AS INTEGER) > 600 THEN 1 END) AS "EXTREMELY_LATE_ARRIVAL",      -- >10 hours late
    
    COUNT(*) AS "TOTAL_RECORDS"
FROM "STAGING_FLIGHTS_RAW";

-- Detailed Time Validation Query - Find all invalid time values
SELECT 
    "TRANSACTIONID",
    "DEPTIME",
    "ARRTIME", 
    "CRSDEPTIME",
    "CRSARRTIME",
    "WHEELSOFF",
    "WHEELSON",
    
    -- Flag invalid times
    CASE WHEN TRY_CAST("DEPTIME" AS INTEGER) >= 2400 THEN 'INVALID_2400_PLUS' 
         WHEN MOD(TRY_CAST("DEPTIME" AS INTEGER), 100) >= 60 THEN 'INVALID_MINUTES'
         ELSE 'VALID' END AS "DEPTIME_STATUS",
         
    CASE WHEN TRY_CAST("ARRTIME" AS INTEGER) >= 2400 THEN 'INVALID_2400_PLUS'
         WHEN MOD(TRY_CAST("ARRTIME" AS INTEGER), 100) >= 60 THEN 'INVALID_MINUTES' 
         ELSE 'VALID' END AS "ARRTIME_STATUS",
         
    CASE WHEN TRY_CAST("CRSDEPTIME" AS INTEGER) >= 2400 THEN 'INVALID_2400_PLUS'
         WHEN MOD(TRY_CAST("CRSDEPTIME" AS INTEGER), 100) >= 60 THEN 'INVALID_MINUTES'
         ELSE 'VALID' END AS "CRSDEPTIME_STATUS",
         
    CASE WHEN TRY_CAST("CRSARRTIME" AS INTEGER) >= 2400 THEN 'INVALID_2400_PLUS'
         WHEN MOD(TRY_CAST("CRSARRTIME" AS INTEGER), 100) >= 60 THEN 'INVALID_MINUTES'
         ELSE 'VALID' END AS "CRSARRTIME_STATUS"

FROM "STAGING_FLIGHTS_RAW"
WHERE TRY_CAST("DEPTIME" AS INTEGER) >= 2400 
   OR TRY_CAST("ARRTIME" AS INTEGER) >= 2400
   OR TRY_CAST("CRSDEPTIME" AS INTEGER) >= 2400  
   OR TRY_CAST("CRSARRTIME" AS INTEGER) >= 2400
   OR TRY_CAST("WHEELSOFF" AS INTEGER) >= 2400
   OR TRY_CAST("WHEELSON" AS INTEGER) >= 2400
   OR MOD(TRY_CAST("DEPTIME" AS INTEGER), 100) >= 60
   OR MOD(TRY_CAST("ARRTIME" AS INTEGER), 100) >= 60
   OR MOD(TRY_CAST("CRSDEPTIME" AS INTEGER), 100) >= 60
   OR MOD(TRY_CAST("CRSARRTIME" AS INTEGER), 100) >= 60;

-- Issue 4: Flight Number Quality Issues
-- Problem: Flight numbers should be numeric and within reasonable ranges
SELECT 
    'Flight Number Quality' AS "ISSUE_TYPE",
    COUNT(CASE WHEN "FLIGHTNUM" IS NULL OR TRIM("FLIGHTNUM") = '' THEN 1 END) AS "MISSING_FLIGHTNUM",
    COUNT(CASE WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) IS NULL AND "FLIGHTNUM" IS NOT NULL THEN 1 END) AS "NON_NUMERIC_FLIGHTNUM",
    COUNT(CASE WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) = 0 THEN 1 END) AS "ZERO_FLIGHTNUM",
    COUNT(CASE WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) < 0 THEN 1 END) AS "NEGATIVE_FLIGHTNUM",
    COUNT(CASE WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) > 9999 THEN 1 END) AS "EXCESSIVE_FLIGHTNUM",  -- Most airlines use 1-4 digits
    COUNT(CASE WHEN LENGTH("FLIGHTNUM") != LENGTH(LTRIM("FLIGHTNUM", '0')) + LENGTH("FLIGHTNUM") - LENGTH(REPLACE("FLIGHTNUM", '0', '')) THEN 1 END) AS "LEADING_ZEROS_LOST",
    COUNT(*) AS "TOTAL_RECORDS"
FROM "STAGING_FLIGHTS_RAW";

-- Detailed Flight Number Analysis
SELECT 
    "FLIGHTNUM",
    COUNT(*) AS "RECORD_COUNT",
    CASE 
        WHEN "FLIGHTNUM" IS NULL OR TRIM("FLIGHTNUM") = '' THEN 'MISSING'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) IS NULL THEN 'NON_NUMERIC'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) = 0 THEN 'ZERO_VALUE'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) < 0 THEN 'NEGATIVE'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) BETWEEN 1 AND 99 THEN 'SINGLE_DOUBLE_DIGIT'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) BETWEEN 100 AND 999 THEN 'TRIPLE_DIGIT'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) BETWEEN 1000 AND 9999 THEN 'FOUR_DIGIT'
        WHEN TRY_CAST("FLIGHTNUM" AS INTEGER) > 9999 THEN 'EXCESSIVE_DIGITS'
        ELSE 'OTHER'
    END AS "FLIGHTNUM_CATEGORY"
FROM "STAGING_FLIGHTS_RAW"
GROUP BY "FLIGHTNUM"
ORDER BY "RECORD_COUNT" DESC, TRY_CAST("FLIGHTNUM" AS INTEGER);

-- Issue 5: Tail Number Standardization Issues
-- Problem: Various non-standard formats (-N963D, NKNO, UNKNOW, blanks)
SELECT 
    'Tail Number Quality' AS "ISSUE_TYPE",
    COUNT(CASE WHEN "TAILNUM" IS NULL OR TRIM("TAILNUM") = '' THEN 1 END) AS "MISSING_TAILNUM",
    COUNT(CASE WHEN "TAILNUM" LIKE 'UNKNOW%' THEN 1 END) AS "UNKNOWN_TAILNUM",
    COUNT(CASE WHEN "TAILNUM" LIKE '-%' THEN 1 END) AS "INVALID_PREFIX_TAILNUM",
    COUNT(CASE WHEN LENGTH("TAILNUM") < 3 AND "TAILNUM" IS NOT NULL THEN 1 END) AS "TOO_SHORT_TAILNUM",
    COUNT(*) AS "TOTAL_RECORDS"
FROM "STAGING_FLIGHTS_RAW";

-- Issue 6: Flight Date Quality Issues
-- Problem: FLIGHTDATE in YYYYMMDD format needs validation
-- Sample values: 19920912, 20040903, 20010103, etc.
SELECT 
    'Flight Date Quality' AS "ISSUE_TYPE",
    COUNT(CASE WHEN "FLIGHTDATE" IS NULL OR TRIM("FLIGHTDATE") = '' THEN 1 END) AS "MISSING_FLIGHTDATE",
    COUNT(CASE WHEN LENGTH("FLIGHTDATE") != 8 THEN 1 END) AS "INCORRECT_DATE_LENGTH",
    COUNT(CASE WHEN TRY_CAST("FLIGHTDATE" AS INTEGER) IS NULL AND "FLIGHTDATE" IS NOT NULL THEN 1 END) AS "NON_NUMERIC_DATE",
    COUNT(CASE WHEN TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') IS NULL AND "FLIGHTDATE" IS NOT NULL THEN 1 END) AS "INVALID_DATE_VALUES",
    
    -- Date range validation
    COUNT(CASE WHEN TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') < '1980-01-01' THEN 1 END) AS "TOO_OLD_DATES",
    COUNT(CASE WHEN TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') > CURRENT_DATE() + 365 THEN 1 END) AS "FUTURE_DATES",
    
    -- Year validation
    COUNT(CASE WHEN SUBSTR("FLIGHTDATE", 1, 4)::INTEGER < 1980 THEN 1 END) AS "PRE_1980_YEARS",
    COUNT(CASE WHEN SUBSTR("FLIGHTDATE", 1, 4)::INTEGER > YEAR(CURRENT_DATE()) + 1 THEN 1 END) AS "FUTURE_YEARS",
    
    -- Month validation (should be 01-12)
    COUNT(CASE WHEN SUBSTR("FLIGHTDATE", 5, 2)::INTEGER NOT BETWEEN 1 AND 12 THEN 1 END) AS "INVALID_MONTHS",
    
    -- Day validation (should be 01-31)
    COUNT(CASE WHEN SUBSTR("FLIGHTDATE", 7, 2)::INTEGER NOT BETWEEN 1 AND 31 THEN 1 END) AS "INVALID_DAYS",
    
    COUNT(*) AS "TOTAL_RECORDS"
FROM "STAGING_FLIGHTS_RAW";

-- Detailed FLIGHTDATE Analysis
SELECT 
    "FLIGHTDATE",
    TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') AS "PARSED_DATE",
    SUBSTR("FLIGHTDATE", 1, 4) AS "YEAR_PART",
    SUBSTR("FLIGHTDATE", 5, 2) AS "MONTH_PART", 
    SUBSTR("FLIGHTDATE", 7, 2) AS "DAY_PART",
    
    CASE 
        WHEN "FLIGHTDATE" IS NULL OR TRIM("FLIGHTDATE") = '' THEN 'MISSING'
        WHEN LENGTH("FLIGHTDATE") != 8 THEN 'WRONG_LENGTH'
        WHEN TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') IS NULL THEN 'INVALID_DATE'
        WHEN TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') < '1980-01-01' THEN 'TOO_OLD'
        WHEN TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') > CURRENT_DATE() + 365 THEN 'FUTURE_DATE'
        WHEN SUBSTR("FLIGHTDATE", 5, 2)::INTEGER NOT BETWEEN 1 AND 12 THEN 'INVALID_MONTH'
        WHEN SUBSTR("FLIGHTDATE", 7, 2)::INTEGER NOT BETWEEN 1 AND 31 THEN 'INVALID_DAY'
        ELSE 'VALID'
    END AS "DATE_QUALITY_STATUS",
    
    COUNT(*) AS "RECORD_COUNT"
    
FROM "STAGING_FLIGHTS_RAW"
WHERE "FLIGHTDATE" IS NOT NULL
GROUP BY "FLIGHTDATE", TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD'), 
         SUBSTR("FLIGHTDATE", 1, 4), SUBSTR("FLIGHTDATE", 5, 2), SUBSTR("FLIGHTDATE", 7, 2)
HAVING TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') IS NULL 
    OR TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') < '1980-01-01'
    OR TRY_TO_DATE("FLIGHTDATE", 'YYYYMMDD') > CURRENT_DATE() + 365
    OR LENGTH("FLIGHTDATE") != 8
ORDER BY "RECORD_COUNT" DESC;

-- Issue 7: Distance Format Inconsistencies
-- Problem: "259 miles" vs numeric values
SELECT 
    'Distance Format Issues' AS "ISSUE_TYPE",
    COUNT(CASE WHEN "DISTANCE" LIKE '%miles%' THEN 1 END) AS "TEXT_FORMAT_DISTANCE",
    COUNT(CASE WHEN TRY_CAST("DISTANCE" AS NUMBER) IS NULL AND "DISTANCE" IS NOT NULL THEN 1 END) AS "NON_NUMERIC_DISTANCE",
    COUNT(*) AS "TOTAL_RECORDS"
FROM "STAGING_FLIGHTS_RAW";

-- ====================
-- 2. BUSINESS RULES IMPLEMENTATION
-- ====================

-- Rule 1: Standardize Boolean Values
CREATE OR REPLACE VIEW "VW_STANDARDIZED_BOOLEANS" AS
SELECT 
    "TRANSACTIONID",
    -- Standardize CANCELLED field
    CASE 
        WHEN UPPER(TRIM("CANCELLED")) IN ('TRUE', '1', 'T', 'Y', 'YES') THEN 1
        WHEN UPPER(TRIM("CANCELLED")) IN ('FALSE', '0', 'F', 'N', 'NO') THEN 0
        ELSE NULL
    END AS "CANCELLED_STD",
    
    -- Standardize DIVERTED field  
    CASE 
        WHEN UPPER(TRIM("DIVERTED")) IN ('TRUE', '1', 'T', 'Y', 'YES') THEN 1
        WHEN UPPER(TRIM("DIVERTED")) IN ('FALSE', '0', 'F', 'N', 'NO') THEN 0
        ELSE NULL
    END AS "DIVERTED_STD",
    
    -- Original values for comparison
    "CANCELLED" AS "CANCELLED_ORIGINAL",
    "DIVERTED" AS "DIVERTED_ORIGINAL"
FROM "STAGING_FLIGHTS_RAW";

-- Rule 2: Clean Text Fields
CREATE OR REPLACE VIEW "VW_CLEANED_TEXT_FIELDS" AS
SELECT 
    "TRANSACTIONID",
    
    -- Clean airline name by removing code prefix
    CASE 
        WHEN "AIRLINENAME" LIKE '%:%' 
        THEN TRIM(SPLIT_PART("AIRLINENAME", ':', 2))
        ELSE TRIM("AIRLINENAME")
    END AS "AIRLINENAME_CLEAN",
    
    -- Clean origin airport name
    CASE 
        WHEN "ORIGAIRPORTNAME" LIKE '%:%' 
        THEN TRIM(SPLIT_PART("ORIGAIRPORTNAME", ':', 2))
        ELSE TRIM("ORIGAIRPORTNAME")
    END AS "ORIGAIRPORTNAME_CLEAN",
    
    -- Clean destination airport name
    CASE 
        WHEN "DESTAIRPORTNAME" LIKE '%:%' 
        THEN TRIM(SPLIT_PART("DESTAIRPORTNAME", ':', 2))
        ELSE TRIM("DESTAIRPORTNAME")
    END AS "DESTAIRPORTNAME_CLEAN",
    
    -- Original values for comparison
    "AIRLINENAME" AS "AIRLINENAME_ORIGINAL",
    "ORIGAIRPORTNAME" AS "ORIGAIRPORTNAME_ORIGINAL", 
    "DESTAIRPORTNAME" AS "DESTAIRPORTNAME_ORIGINAL"
FROM "STAGING_FLIGHTS_RAW";

-- Rule 3: Time Format Standardization (Enhanced with 2400 correction)
CREATE OR REPLACE VIEW "VW_STANDARDIZED_TIMES" AS
SELECT 
    "TRANSACTIONID",
    
    -- Convert HHMM integer format to proper TIME with 2400 correction
    TRY_CAST(
        CASE 
            WHEN "DEPTIME" IS NULL OR TRIM("DEPTIME") = '' THEN NULL
            WHEN TRY_CAST("DEPTIME" AS INTEGER) = 2400 THEN TIME_FROM_PARTS(0, 0, 0)  -- 2400 = 00:00 next day
            WHEN TRY_CAST("DEPTIME" AS INTEGER) >= 2400 THEN NULL  -- Invalid time
            WHEN MOD(TRY_CAST("DEPTIME" AS INTEGER), 100) >= 60 THEN NULL  -- Invalid minutes
            WHEN LENGTH(TRIM("DEPTIME")) <= 4 AND TRY_CAST("DEPTIME" AS INTEGER) < 2400
            THEN TIME_FROM_PARTS(
                FLOOR(TRY_CAST("DEPTIME" AS INTEGER) / 100),
                MOD(TRY_CAST("DEPTIME" AS INTEGER), 100),
                0
            )
            ELSE NULL
        END AS TIME
    ) AS "DEPTIME_STD",
    
    TRY_CAST(
        CASE 
            WHEN "ARRTIME" IS NULL OR TRIM("ARRTIME") = '' THEN NULL
            WHEN TRY_CAST("ARRTIME" AS INTEGER) = 2400 THEN TIME_FROM_PARTS(0, 0, 0)  -- 2400 = 00:00 next day
            WHEN TRY_CAST("ARRTIME" AS INTEGER) >= 2400 THEN NULL  -- Invalid time
            WHEN MOD(TRY_CAST("ARRTIME" AS INTEGER), 100) >= 60 THEN NULL  -- Invalid minutes
            WHEN LENGTH(TRIM("ARRTIME")) <= 4 AND TRY_CAST("ARRTIME" AS INTEGER) < 2400
            THEN TIME_FROM_PARTS(
                FLOOR(TRY_CAST("ARRTIME" AS INTEGER) / 100),
                MOD(TRY_CAST("ARRTIME" AS INTEGER), 100),
                0
            )
            ELSE NULL
        END AS TIME
    ) AS "ARRTIME_STD",
    
    TRY_CAST(
        CASE 
            WHEN "CRSDEPTIME" IS NULL OR TRIM("CRSDEPTIME") = '' THEN NULL
            WHEN TRY_CAST("CRSDEPTIME" AS INTEGER) = 2400 THEN TIME_FROM_PARTS(0, 0, 0)  -- 2400 = 00:00
            WHEN TRY_CAST("CRSDEPTIME" AS INTEGER) >= 2400 THEN NULL  -- Invalid time
            WHEN MOD(TRY_CAST("CRSDEPTIME" AS INTEGER), 100) >= 60 THEN NULL  -- Invalid minutes
            WHEN LENGTH(TRIM("CRSDEPTIME")) <= 4 AND TRY_CAST("CRSDEPTIME" AS INTEGER) < 2400
            THEN TIME_FROM_PARTS(
                FLOOR(TRY_CAST("CRSDEPTIME" AS INTEGER) / 100),
                MOD(TRY_CAST("CRSDEPTIME" AS INTEGER), 100),
                0
            )
            ELSE NULL
        END AS TIME
    ) AS "CRSDEPTIME_STD",
    
    TRY_CAST(
        CASE 
            WHEN "CRSARRTIME" IS NULL OR TRIM("CRSARRTIME") = '' THEN NULL
            WHEN TRY_CAST("CRSARRTIME" AS INTEGER) = 2400 THEN TIME_FROM_PARTS(0, 0, 0)  -- 2400 = 00:00
            WHEN TRY_CAST("CRSARRTIME" AS INTEGER) >= 2400 THEN NULL  -- Invalid time
            WHEN MOD(TRY_CAST("CRSARRTIME" AS INTEGER), 100) >= 60 THEN NULL  -- Invalid minutes
            WHEN LENGTH(TRIM("CRSARRTIME")) <= 4 AND TRY_CAST("CRSARRTIME" AS INTEGER) < 2400
            THEN TIME_FROM_PARTS(
                FLOOR(TRY_CAST("CRSARRTIME" AS INTEGER) / 100),
                MOD(TRY_CAST("CRSARRTIME" AS INTEGER), 100),
                0
            )
            ELSE NULL
        END AS TIME
    ) AS "CRSARRTIME_STD",
    
    -- Additional time fields with same logic
    TRY_CAST(
        CASE 
            WHEN "WHEELSOFF" IS NULL OR TRIM("WHEELSOFF") = '' THEN NULL
            WHEN TRY_CAST("WHEELSOFF" AS INTEGER) = 2400 THEN TIME_FROM_PARTS(0, 0, 0)
            WHEN TRY_CAST("WHEELSOFF" AS INTEGER) >= 2400 THEN NULL
            WHEN MOD(TRY_CAST("WHEELSOFF" AS INTEGER), 100) >= 60 THEN NULL
            WHEN LENGTH(TRIM("WHEELSOFF")) <= 4 AND TRY_CAST("WHEELSOFF" AS INTEGER) < 2400
            THEN TIME_FROM_PARTS(
                FLOOR(TRY_CAST("WHEELSOFF" AS INTEGER) / 100),
                MOD(TRY_CAST("WHEELSOFF" AS INTEGER), 100),
                0
            )
            ELSE NULL
        END AS TIME
    ) AS "WHEELSOFF_STD",
    
    TRY_CAST(
        CASE 
            WHEN "WHEELSON" IS NULL OR TRIM("WHEELSON") = '' THEN NULL
            WHEN TRY_CAST("WHEELSON" AS INTEGER) = 2400 THEN TIME_FROM_PARTS(0, 0, 0)
            WHEN TRY_CAST("WHEELSON" AS INTEGER) >= 2400 THEN NULL
            WHEN MOD(TRY_CAST("WHEELSON" AS INTEGER), 100) >= 60 THEN NULL
            WHEN LENGTH(TRIM("WHEELSON")) <= 4 AND TRY_CAST("WHEELSON" AS INTEGER) < 2400
            THEN TIME_FROM_PARTS(
                FLOOR(TRY_CAST("WHEELSON" AS INTEGER) / 100),
                MOD(TRY_CAST("WHEELSON" AS INTEGER), 100),
                0
            )
            ELSE NULL
        END AS TIME
    ) AS "WHEELSON_STD",
    
    -- Time validation flags
    CASE WHEN TRY_CAST("DEPTIME" AS INTEGER) = 2400 THEN 'CORRECTED_2400_TO_0000'
         WHEN TRY_CAST("DEPTIME" AS INTEGER) > 2400 THEN 'INVALID_ABOVE_2400'
         WHEN MOD(TRY_CAST("DEPTIME" AS INTEGER), 100) >= 60 THEN 'INVALID_MINUTES' 
         ELSE 'VALID' END AS "DEPTIME_QUALITY_FLAG",
         
    CASE WHEN TRY_CAST("ARRTIME" AS INTEGER) = 2400 THEN 'CORRECTED_2400_TO_0000'
         WHEN TRY_CAST("ARRTIME" AS INTEGER) > 2400 THEN 'INVALID_ABOVE_2400'
         WHEN MOD(TRY_CAST("ARRTIME" AS INTEGER), 100) >= 60 THEN 'INVALID_MINUTES'
         ELSE 'VALID' END AS "ARRTIME_QUALITY_FLAG",
    
    -- Original values
    "DEPTIME" AS "DEPTIME_ORIGINAL",
    "ARRTIME" AS "ARRTIME_ORIGINAL",
    "CRSDEPTIME" AS "CRSDEPTIME_ORIGINAL",
    "CRSARRTIME" AS "CRSARRTIME_ORIGINAL",
    "WHEELSOFF" AS "WHEELSOFF_ORIGINAL",
    "WHEELSON" AS "WHEELSON_ORIGINAL"
FROM "STAGING_FLIGHTS_RAW";

-- Business Rule: Next Day Arrival Detection (Enhanced)
-- Problem: When ARRTIME < DEPTIME, it indicates next-day arrival
CREATE OR REPLACE VIEW "VW_NEXT_DAY_ARRIVAL_LOGIC" AS
SELECT 
    "TRANSACTIONID",
    "DEPTIME",
    "ARRTIME", 
    "CRSDEPTIME",
    "CRSARRTIME",
    
    -- Next day arrival detection
    CASE 
        WHEN TRY_CAST("ARRTIME" AS INTEGER) < TRY_CAST("DEPTIME" AS INTEGER) 
             AND "ARRTIME" IS NOT NULL 
             AND "DEPTIME" IS NOT NULL 
             AND TRY_CAST("ARRTIME" AS INTEGER) < 2400
             AND TRY_CAST("DEPTIME" AS INTEGER) < 2400
        THEN 1
        WHEN TRY_CAST("ARRTIME" AS INTEGER) = 2400 
             AND TRY_CAST("DEPTIME" AS INTEGER) > 1200  -- Departed after noon, arrived at midnight
        THEN 1  
        ELSE 0
    END AS "IS_NEXT_DAY_ARRIVAL",
    
    -- Time correction needed flag
    CASE 
        WHEN TRY_CAST("DEPTIME" AS INTEGER) = 2400 
          OR TRY_CAST("ARRTIME" AS INTEGER) = 2400
          OR TRY_CAST("CRSDEPTIME" AS INTEGER) = 2400
          OR TRY_CAST("CRSARRTIME" AS INTEGER) = 2400
        THEN 'NEEDS_2400_CORRECTION'
        WHEN TRY_CAST("DEPTIME" AS INTEGER) > 2400
          OR TRY_CAST("ARRTIME" AS INTEGER) > 2400  
        THEN 'INVALID_TIME_VALUE'
        ELSE 'NO_CORRECTION_NEEDED'
    END AS "TIME_CORRECTION_STATUS"
    
FROM "STAGING_FLIGHTS_RAW"
WHERE "DEPTIME" IS NOT NULL OR "ARRTIME" IS NOT NULL;
